#ifndef GLOBALS_H
#define GLOBALS_H

#include <Arduboy2.h>
#include "Game.hpp"

#define TILE_SIZE 16

#define SCREEN_WIDTH       128
#define SCREEN_HEIGHT       64
#define SCREEN_HALF_WIDTH   64 // SCREEN_WIDTH  / 2
#define SCREEN_HALF_HEIGHT  32 // SCREEN_HEIGHT / 2

#define MAP_CANVAS_WIDTH      112 // SCREEN_WIDTH - 16
#define MAP_CANVAS_HEIGHT      64 // SCREEN_HEIGHT
#define MAP_CANVAS_HALF_WIDTH  56 // MAP_CANVAS_WIDTH / 2
#define MAP_CANVAS_HALF_HEIGHT 32 // MAP_CANVAS_HEIGHT / 2
#define MAP_CANVAS_X           16
#define MAP_CANVAS_Y            0

#define PLAYER_WIDTH       16
#define PLAYER_HEIGHT      16
#define PLAYER_HALF_WIDTH   8 // PLAYER_WIDTH  / 2
#define PLAYER_HALF_HEIGHT  8 // PLAYER_HEIGHT / 2

#define PLAYER_CENTER_POS_LEFT   48 // MAP_CANVAS_HALF_WIDTH  - PLAYER_HALF_WIDTH
#define PLAYER_CENTER_POS_RIGHT  64 // MAP_CANVAS_HALF_WIDTH  + PLAYER_HALF_WIDTH
#define PLAYER_CENTER_POS_TOP    24 // MAP_CANVAS_HALF_HEIGHT - PLAYER_HALF_HEIGHT
#define PLAYER_CENTER_POS_BOTTOM 40 // MAP_CANVAS_HALF_HEIGHT + PLAYER_HALF_HEIGHT

#define DEFAULT_TILE 0
#define DEFAULT_PASSIBILITY false

extern Arduboy2 arduboy;
extern Game *game;

extern uint8_t frameCounter;

#endif
